services:
  web:
    build: .
    container_name: poke-invite-web
    restart: unless-stopped
    depends_on:
      - syslog
    env_file:
      - .env
    environment:
      - SYSLOG_ADDRESS=syslog:514
    ports:
      # Exposes the app to your PC's localhost:5000
      - "5000:5000"
    volumes:
      # Keeps your guest list safe on your PC
      - ./guests:/app/guests
      # Allows you to edit the event details live
      - ./config.json:/app/config.json
      - ./lang.json:/app/lang.json
      - ./logs:/app/logs

  syslog:
    # Nova imagem oficial para recebimento de logs
    image: rsyslog/rsyslog-collector:latest
    container_name: poke-invite-syslog
    restart: unless-stopped
    environment:
      # Ativa explicitamente a escuta do servidor na porta 514
      - ENABLE_UDP=on
    ports:
      - "514:514/udp"
    volumes:
      - ./logs/syslog:/var/log